---
driver:
  name: vcenter
  vcenter_username: <%= ENV['VCENTER_USER'] || "administrator@vsphere.local" %>
  vcenter_password: <%= ENV['VCENTER_PASSWORD'] || "Good4bye!" %>
  vcenter_host:  "172.16.20.2"
  vcenter_disable_ssl_verify: true

provisioner:
  name: chef_zero
  sudo_command: sudo

verifier:
  name: inspec

platforms:
  - name: ubuntu-1604
    transport:
      username: admini
      password: admini
    driver_config:
      template: ubuntu16-template
      targethost: 172.16.20.3
      datacenter: "Datacenter"

  - name: centos-7
    transport:
      username: root
      password: admini
    driver_config:
      template: centos7-template
      targethost: 172.16.20.3
      datacenter: "Datacenter"

suites:
- name: default
  run_list:
  - recipe[vim::default]
