---
driver:
  name: vcenter
  vcenter_username:   <%= ENV['VCENTER_USER'] || "administrator@vsphere.local" %>
  vcenter_password: <%= ENV['VCENTER_PASSWORD'] || "Good4bye!" %>
  vcenter_host: <%= ENV['AWS'] || '172.16.20.2' %>
  vcenter_disable_ssl_verify: true

provisioner:
  name: chef_zero
  sudo_command: sudo

verifier:
  name: inspec

transport:
  username: root
  password: admini

platforms:
  - name: centos-7
    driver_config:
      <%= ENV['VCENTER_HOST'] || "targethost: 172.16.20.42" %>
      template: centos7-template
      datacenter: "Datacenter"

suites:
- name: default
  run_list:
  - recipe[vim::default]
